#!/usr/bin/env python3
from __future__ import annotations

import json
import math
import re
import subprocess
from pathlib import Path

ROOT      = Path(__file__).resolve().parent.parent
MSX_DIR   = ROOT / 'msx'
DATA_DIR  = ROOT / 'data'
BUILD_DIR = ROOT / 'build'
TOOLS_DIR = ROOT / 'tools'

CODE_ASM = MSX_DIR / 'player_rom.asm'
SONG_INC = MSX_DIR / 'song_table.inc'
CODE_BIN = BUILD_DIR / 'player_rom_code.bin'
ROM_OUT  = BUILD_DIR / 'player.rom'

Z80ASM = TOOLS_DIR / 'z80asm.exe' if (TOOLS_DIR / 'z80asm.exe').exists() else 'z80asm'

BANK_SIZE        = 0x2000   # 8KB (Konami mapper granularity)
ROM_SIZE         = 0x20000  # 128KB
DATA_BASE_OFFSET = 0x2000   # bank 1 starts here (bank 0 is code)


def get_display_name(mps_name: str, name_map: dict) -> str:
    """Look up display name from songs.json, fallback to MPS stem."""
    if mps_name in name_map:
        return name_map[mps_name]
    # Strip leading 2-digit index added by convert_msx.py
    stem = re.sub(r'^\d{2}', '', mps_name.upper().replace('.MPS', ''))
    return stem or mps_name.replace('.MPS', '')


def build_table(song_infos: list[tuple[str, int, int, int]],
                display_names: list[str]) -> None:
    n = len(song_infos)
    lines = ['; Auto-generated by tools/build_msx_rom.py']

    # SONG_COUNT + song_table
    lines.append(f'SONG_COUNT: equ {n}')
    lines.append('song_table:')
    for name, bank, addr, size in song_infos:
        lines.append(
            f'        db 0x{bank:02X}, 0x{addr & 0xFF:02X},'
            f' 0x{(addr >> 8) & 0xFF:02X} ; {name} ({size} bytes)'
        )

    # msg_screen: header + numbered song list
    title = 'MSX PSG PLAYER'
    sep   = '=' * (len(title) + 4)
    lines += [
        'msg_screen:',
        '        db      13,10',
        f'        db      "  * {title} *",13,10',
        f'        db      "  {sep}",13,10',
        '        db      13,10',
        '        db      " 0) Play All",13,10',
    ]
    for i, name in enumerate(display_names, 1):
        lines.append(f'        db      " {i}) {name}",13,10')
    lines.append('        db      0')

    # msg_help
    lines += [
        'msg_help:',
        f'        db      "0-{n}:Select  Any:Stop",0',
    ]

    # song_name_table + individual strings
    lines.append('song_name_table:')
    for i in range(n):
        lines.append(f'        dw      song_name_{i}')
    for i, name in enumerate(display_names):
        lines += [f'song_name_{i}:', f'        db      "{name}",0']

    SONG_INC.write_text('\n'.join(lines) + '\n', encoding='ascii')


def main() -> int:
    BUILD_DIR.mkdir(parents=True, exist_ok=True)

    songs_json = DATA_DIR / 'songs.json'
    name_map: dict = json.loads(songs_json.read_text(encoding='utf-8')) if songs_json.exists() else {}

    blobs: list[tuple[str, bytes]] = []
    for p in sorted(DATA_DIR.glob('*.MPS')):
        blobs.append((p.name, p.read_bytes()))

    if not blobs:
        raise FileNotFoundError(f'No .MPS files found in {DATA_DIR}. Run make convert-msx first.')

    display_names = [get_display_name(name, name_map) for name, _ in blobs]

    total_song_bytes    = sum(len(b) for _, b in blobs)
    required_data_banks = math.ceil(total_song_bytes / BANK_SIZE)
    required_total_banks = 1 + required_data_banks
    if required_total_banks > (ROM_SIZE // BANK_SIZE):
        raise RuntimeError(
            f'Song data too large: need {required_total_banks} banks, '
            f'have {ROM_SIZE // BANK_SIZE}'
        )

    # Pack songs into ROM data area (bank 1+)
    song_infos: list[tuple[str, int, int, int]] = []
    offset = 0
    for name, blob in blobs:
        bank    = 1 + (offset // BANK_SIZE)
        in_bank = offset % BANK_SIZE
        addr    = 0xA000 + in_bank
        song_infos.append((name, bank, addr, len(blob)))
        offset += len(blob)

    build_table(song_infos, display_names)
    for name, dname in zip([n for n, _ in blobs], display_names):
        print(f'  {name} -> "{dname}"')

    # Assemble code bank
    subprocess.run(
        [str(Z80ASM), '-I', str(MSX_DIR), '-o', str(CODE_BIN), str(CODE_ASM)],
        check=True
    )
    code = CODE_BIN.read_bytes()
    if len(code) > BANK_SIZE:
        raise RuntimeError(f'Code too large for bank0: {len(code)} bytes')

    rom = bytearray([0xFF] * ROM_SIZE)
    rom[0:len(code)] = code

    write_off = DATA_BASE_OFFSET
    for _name, blob in blobs:
        rom[write_off:write_off + len(blob)] = blob
        write_off += len(blob)

    with open(ROM_OUT, 'wb') as f:
        f.write(rom)
    print(f'ROM: {ROM_OUT}  ({len(code)}B code, {total_song_bytes}B songs,'
          f' {required_total_banks}/{ROM_SIZE // BANK_SIZE} banks)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
