#!/usr/bin/env python3
from __future__ import annotations

import math
import os
import subprocess
from pathlib import Path

ROOT = Path('/Users/honux/HobbyProjects/msx-music')
MSX_DIR = ROOT / 'msx'
DATA_DIR = ROOT / 'data'
BUILD_DIR = ROOT / 'build'

CODE_ASM = MSX_DIR / 'player_rom.asm'
SONG_INC = MSX_DIR / 'song_table.inc'
CODE_BIN = BUILD_DIR / 'player_rom_code.bin'
ROM_OUT = BUILD_DIR / 'player.rom'

BANK_SIZE = 0x2000  # 8KB (Konami mapper granularity)
ROM_SIZE = 0x20000  # 128KB
DATA_BASE_OFFSET = 0x2000  # bank 1 starts here (bank 0 is code)

SONGS = [
    ('MOHENJO.MPS', '01 Usas [Mohenjo daro].vgz'),
    ('JUBA.MPS',    '02 Usas [Juba ruins].vgz'),
]


def build_table(song_infos: list[tuple[str, int, int, int]]) -> None:
    lines = []
    lines.append('; Auto-generated by tools/build_msx_rom.py')
    lines.append(f'SONG_COUNT: equ {len(song_infos)}')
    lines.append('song_table:')
    for name, bank, addr, size in song_infos:
        lines.append(f'        db 0x{bank:02X}, 0x{addr & 0xFF:02X}, 0x{(addr >> 8) & 0xFF:02X} ; {name} ({size} bytes)')
    SONG_INC.write_text('\n'.join(lines) + '\n', encoding='ascii')


def main() -> int:
    BUILD_DIR.mkdir(parents=True, exist_ok=True)

    blobs: list[tuple[str, bytes]] = []
    for mps_name, _orig in SONGS:
        p = DATA_DIR / mps_name
        if not p.exists():
            raise FileNotFoundError(f'missing song file: {p}')
        blobs.append((mps_name, p.read_bytes()))

    total_song_bytes = sum(len(b) for _, b in blobs)
    required_data_banks = math.ceil(total_song_bytes / BANK_SIZE)
    required_total_banks = 1 + required_data_banks  # + bank0 code
    if required_total_banks > (ROM_SIZE // BANK_SIZE):
        raise RuntimeError(f'song data too large: need {required_total_banks} banks, have {ROM_SIZE // BANK_SIZE}')

    # Pack songs into ROM data area (bank 1+)
    song_infos: list[tuple[str, int, int, int]] = []
    offset = 0
    for name, blob in blobs:
        bank = 1 + (offset // BANK_SIZE)
        in_bank = offset % BANK_SIZE
        addr = 0xA000 + in_bank
        song_infos.append((name, bank, addr, len(blob)))
        offset += len(blob)

    build_table(song_infos)

    # Assemble code bank
    subprocess.run(['z80asm', '-I', str(MSX_DIR), '-o', str(CODE_BIN), str(CODE_ASM)], check=True)
    code = CODE_BIN.read_bytes()
    if len(code) > BANK_SIZE:
        raise RuntimeError(f'code too large for bank0: {len(code)} bytes')

    rom = bytearray([0xFF] * ROM_SIZE)
    rom[0:len(code)] = code

    write_off = DATA_BASE_OFFSET
    for _name, blob in blobs:
        rom[write_off:write_off + len(blob)] = blob
        write_off += len(blob)

    ROM_OUT.write_bytes(rom)

    print(f'ROM written: {ROM_OUT}')
    print(f'Code size: {len(code)} bytes')
    print(f'Song bytes: {total_song_bytes} bytes')
    print(f'Banks used: code=1, data={required_data_banks}, total={required_total_banks} / {ROM_SIZE // BANK_SIZE}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
