#!/usr/bin/env python3
"""Generate msx/menu_names.inc by scanning vgz/ directory directly.

Display name = VGZ file stem (e.g. "01 Majou Densetsu")
FCB name     = same formula as convert_msx.py make_mps_name
"""
from __future__ import annotations
import re
from pathlib import Path

ROOT     = Path(__file__).resolve().parent.parent
VGZ_DIR  = ROOT / 'vgz'
MSX_DIR  = ROOT / 'msx'
OUT      = MSX_DIR / 'menu_names.inc'


def make_mps_name(stem: str, index: int) -> str:
    title  = re.sub(r'^\d+\s*', '', stem)
    suffix = re.sub(r'[^A-Za-z0-9]', '', title)[:6].upper()
    return f'{index:02d}{suffix}.MPS'


def fcb_str(mps_name: str) -> str:
    p    = Path(mps_name)
    name = p.stem.upper()[:8].ljust(8)
    ext  = p.suffix.lstrip('.').upper()[:3].ljust(3)
    return name + ext


def main() -> int:
    vgz_files = sorted(VGZ_DIR.glob('*.vgz'))
    if not vgz_files:
        raise FileNotFoundError(f'No .vgz files found in {VGZ_DIR}')

    entries = [(make_mps_name(p.stem, i), p.stem)
               for i, p in enumerate(vgz_files, start=1)]
    n = len(entries)

    lines = ['; Auto-generated by tools/gen_menu_names.py -- do not edit']
    lines.append(f'MENU_SONG_COUNT: equ {n}')
    lines.append('')

    lines.append('menu_fcb_table:')
    for mps_name, _ in entries:
        lines.append(f'        db      "{fcb_str(mps_name)}"  ; {mps_name}')
    lines.append('')

    lines.append('menu_name_table:')
    for i in range(n):
        lines.append(f'        dw      menu_name_{i}')
    lines.append('')

    for i, (mps_name, display) in enumerate(entries):
        lines.append(f'menu_name_{i}:')
        lines.append(f'        db      "{display}", 13, 10, "$"')

    OUT.write_text('\n'.join(lines) + '\n', encoding='ascii')
    print(f'Generated {OUT}  ({n} songs)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
